/**
 * Route generator for BunBox
 * Generates a routes.ts file with all page and layout imports
 */

import { join } from "path";
import { mkdir } from "node:fs/promises";
import { scanPageRoutes, scanLayouts } from "./scanner";

/**
 * Convert file path to route path
 */
function filePathToRoute(filePath: string): string {
  let route = filePath
    .replace(/^app\/?/, "")
    .replace(/\/page\.(tsx|ts|jsx|js)$/, "")
    .replace(/page\.(tsx|ts|jsx|js)$/, "")
    .replace(/\/layout\.(tsx|ts|jsx|js)$/, "")
    .replace(/layout\.(tsx|ts|jsx|js)$/, "");

  if (route === "") route = "/";
  else if (!route.startsWith("/")) route = "/" + route;

  return route;
}

/**
 * Generate routes file for client-side hydration
 */
export async function generateRoutesFile(appDir: string) {
  const pageRoutes = await scanPageRoutes(appDir);
  const layouts = await scanLayouts(appDir);

  const imports: string[] = [];
  const routeExports: string[] = [];
  const layoutExports: string[] = [];

  let importCounter = 0;

  // Generate page imports
  for (const route of pageRoutes) {
    const importName = `Page${importCounter++}`;
    // route.filepath is relative to appDir, need to prepend app/
    const importPath = `../app/${route.filepath}`;
    const routePath = filePathToRoute(route.filepath);

    imports.push(`import ${importName} from "${importPath}";`);
    routeExports.push(`  "${routePath}": ${importName}`);
  }

  // Generate layout imports
  for (const [routePath, layoutFile] of layouts.entries()) {
    const importName = `Layout${importCounter++}`;
    // layoutFile is relative to appDir, need to prepend app/
    const importPath = `../app/${layoutFile}`;

    imports.push(`import ${importName} from "${importPath}";`);
    layoutExports.push(`  "${routePath}": ${importName}`);
  }

  // Generate file content
  const content = `/**
 * Auto-generated routes file for BunBox
 * Do not edit this file manually
 */

${imports.join("\n")}

export const routes = {
${routeExports.join(",\n")}
};

export const layouts = {
${layoutExports.join(",\n")}
};
`;

  // Write to .bunbox directory
  const bunboxDir = join(process.cwd(), ".bunbox");
  await mkdir(bunboxDir, { recursive: true });

  const routesPath = join(bunboxDir, "routes.ts");
  await Bun.write(routesPath, content);

  console.log(`📝 Generated routes file: ${routesPath}`);
  return routesPath;
}
